using System.Resources;
using System.Reflection;
using System.Runtime.InteropServices;

// 名称&描述&文件说明&防火墙-名称
[assembly: AssemblyTitle("屏幕共享")]
// 产品名称
[assembly: AssemblyProduct("屏幕共享")]
// 版权
[assembly: AssemblyCopyright("https://github.com/ALI1416/ScreenShare")]
// 合法商标
[assembly: AssemblyTrademark("404z.cn")]
// 防火墙-发布者
[assembly: AssemblyCompany("404z.cn")]
// 文件版本&产品版本
[assembly: AssemblyFileVersion("2.4.0.8")]
// 不显示
[assembly: AssemblyVersion("2.4.0.8")]
[assembly: AssemblyDescription("局域网屏幕共享")]
[assembly: AssemblyConfiguration("retail")]
[assembly: AssemblyCulture("")]
[assembly: NeutralResourcesLanguage("zh-CN")]
[assembly: ComVisible(false)]
[assembly: Guid("000e46c2-90df-48d2-94cb-364bc2514050")]
