//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenShare.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenShare.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;&lt;html lang=&quot;zh-cmn-Hans&quot;&gt;&lt;head&gt;&lt;meta charset=&quot;UTF-8&quot;&gt;&lt;title&gt;屏幕共享&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;h1 align=&quot;center&quot;&gt;屏幕共享&lt;/h1&gt;&lt;h2 align=&quot;center&quot;&gt;版本： 的本地化字符串。
        /// </summary>
        internal static string aboutHtml1 {
            get {
                return ResourceManager.GetString("aboutHtml1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;/h2&gt;&lt;hr&gt;&lt;h3&gt;功能&lt;/h3&gt;&lt;ul&gt;&lt;li&gt;加密传输&lt;/li&gt;&lt;li&gt;支持多显示器&lt;/li&gt;&lt;li&gt;支持高DPI&lt;/li&gt;&lt;li&gt;自定义选择区域&lt;/li&gt;&lt;li&gt;视频尺寸调节&lt;/li&gt;&lt;li&gt;视频质量调节&lt;/li&gt;&lt;li&gt;视频帧数调节&lt;/li&gt;&lt;li&gt;光标显示&lt;/li&gt;&lt;li&gt;视频预览&lt;/li&gt;&lt;li&gt;托盘运行&lt;/li&gt;&lt;/ul&gt;&lt;hr&gt;&lt;h3&gt;作者：ALI1416&lt;/h3&gt;&lt;a href=&quot;https://github.com/ALI1416&quot;target=&quot;_blank&quot;&gt;GitHub&lt;/a&gt; &lt;a href=&quot;https://gitee.com/ALI1416&quot;&gt;Gitee&lt;/a&gt;&lt;hr&gt;&lt;h3&gt;项目：ScreenShare&lt;/h3&gt;&lt;a href=&quot;https://github.com/ALI1416/ScreenShare&quot;&gt;GitHub&lt;/a&gt; &lt;a href=&quot;https://gitee.com/ALI1416/ScreenShare&quot;&gt;Gitee&lt;/a&gt;&lt;hr&gt;&lt;h3&gt;致谢&lt;/h3&gt;&lt;a href=&quot;https://github.com/EslaMx7/ScreenTask&quot;&gt;Es [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string aboutHtml2 {
            get {
                return ResourceManager.GetString("aboutHtml2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cursor {
            get {
                object obj = ResourceManager.GetObject("cursor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;&lt;html lang=&quot;zh-cmn-Hans&quot;&gt;&lt;head&gt;&lt;meta charset=&quot;UTF-8&quot;&gt;&lt;meta http-equiv=&quot;X-UA-Compatible&quot;content=&quot;IE=edge&quot;&gt;&lt;meta name=&quot;viewport&quot;content=&quot;width=device-width, initial-scale=1.0&quot;&gt;&lt;title&gt;屏幕共享&lt;/title&gt;&lt;/head&gt;&lt;body style=&quot;overflow:hidden&quot;&gt;&lt;img id=&quot;img&quot;src=&quot;image.jpg&quot;alt=&quot;网络连接异常&quot;style=&quot;position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);display:none&quot;ondblclick=&quot;end()&quot;&gt;&lt;div id=&quot;div&quot;&gt;&lt;h1&gt;屏幕共享&lt;/h1&gt;&lt;p id=&quot;origin&quot;style=&quot;font-size:20px;&quot;&gt;&lt;/p&gt;&lt;p id=&quot;current&quot;style=&quot;font-size:20px;&quot;&gt;&lt;/p&gt;&lt;button on [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string indexHtml1 {
            get {
                return ResourceManager.GetString("indexHtml1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ;const speed=1000/frame;const img=document.getElementById(&quot;img&quot;);const div=document.getElementById(&quot;div&quot;);const origin=document.getElementById(&quot;origin&quot;);const current=document.getElementById(&quot;current&quot;);let count=0;let refreshImg;origin.innerHTML=&quot;远端视频尺寸：&quot;+imgWidth+&quot;x&quot;+imgHeight+&quot;px，帧率：&quot;+frame+&quot;FPS&quot;;adjustImg();function adjustImg(){if(imgWidth/window.innerWidth&lt;imgHeight/window.innerHeight){img.style.height=&quot;100%&quot;;img.style.width=null}else{img.style.width=&quot;100%&quot;;img.style.height=null}current.innerHTML=&quot;当前屏幕尺 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string indexHtml2 {
            get {
                return ResourceManager.GetString("indexHtml2", resourceCulture);
            }
        }
    }
}
